name: Render TeX
on:
  push:
    branches:
      - daddy
      - gh-actions
jobs:
  render_latex:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            resume.pdf
          name: resume-naufal-${{ steps.date.output.date }}

