name: Release
on:
  push:
    tags:
      - public-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]
jobs:
  render:
    uses: ./.github/workflows/render.yml
  release:
    needs: render
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: resume.pdf
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: resume.pdf
