name: Render TeX
on:
  push:
    branches:
      - daddy
      - gh-actions
  workflow_call:
jobs:
  render_latex:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: resume.pdf
          path: resume.pdf
